[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

# ---- 编译 central（左手）----
[tasks.build-central]
command = "cargo"
args = ["build", "--release", "--bin", "central"]
dependencies = ["install-llvm-tools", "flip-link"]

# ---- 编译 peripheral（右手）----
[tasks.build-peripheral]
command = "cargo"
args = ["build", "--release", "--bin", "peripheral"]
dependencies = ["install-llvm-tools", "flip-link"]

# ---- central 转 hex ----
[tasks.objcopy-central]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = ["objcopy", "--release", "--bin", "central", "--", "-O", "ihex", "rmk-central.hex"]
dependencies = ["build-central"]

# ---- peripheral 转 hex ----
[tasks.objcopy-peripheral]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = ["objcopy", "--release", "--bin", "peripheral", "--", "-O", "ihex", "rmk-peripheral.hex"]
dependencies = ["build-peripheral"]

# ---- central hex 转 uf2 ----
[tasks.uf2-central]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "rmk-central.hex",
    "--output-path",
    "rmk-7angle-central.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-central"]

# ---- peripheral hex 转 uf2 ----
[tasks.uf2-peripheral]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "rmk-peripheral.hex",
    "--output-path",
    "rmk-7angle-peripheral.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-peripheral"]

# ---- 一次编两个 uf2 ----
[tasks.uf2]
dependencies = ["uf2-central", "uf2-peripheral"]
